In [1]:
def github() -> str:
    """
    This function returns a link to the GitHub repository containing solutions.

    Returns:
        str: The URL to the GitHub repository.
    """
    return "https://github.com/anasfathul/ECON481/blob/main/ECON481_HW3.py"

In [3]:
import numpy as np
import pandas as pd

In [11]:
# Exercise 1
import pandas as pd

def import_yearly_data(years: list) -> pd.DataFrame:
    """
    This function takes as its argument a list of years.
    It returns a concatenated DataFrame of the Direct Emitters tab of each of those year's EPA excel sheet.
    It will add a variable year that references the year from which the data is pulled and no column use as index.
    """
    full_df = []

    for year in years:
        exl_path = f"https://lukashager.netlify.app/econ-481/data/ghgp_data_{year}.xlsx"
        temp_df = pd.read_excel(exl_path, header=3, sheet_name='Direct Emitters')
        temp_df['year'] = year
        full_df.append(temp_df)

    
    return pd.concat(full_df)

In [35]:
# test

test1 = import_yearly_data([2019, 2020])
test1

,Facility Id,FRS Id,Facility Name,City,State,Zip Code,Address,County,Latitude,Longitude,...,Underground Coal Mines,Zinc Production,Municipal Landfills,Industrial Wastewater Treatment,Manufacture of Electric Transmission and Distribution Equipment,Industrial Waste Landfills,Is some CO2 collected on-site and used to manufacture other products and therefore not emitted from the affected manufacturing process unit(s)? (as reported under Subpart G or S),"Is some CO2 reported as emissions from the affected manufacturing process unit(s) under Subpart AA, G or P collected and transferred off-site or injected (as reported under Subpart PP)?",Does the facility employ continuous emissions monitoring?,year
0,1004377,1.100438e+11,121 REGIONAL DISPOSAL FACILITY,MELISSA,TX,75454,3820 SAM RAYBURN HIGHWAY,COLLIN COUNTY,33.298570,-96.535860,...,NaN,NaN,518680.25,NaN,NaN,NaN,N,N,N,2019
1,1000112,1.100712e+11,23rd and 3rd,BROOKLYN,NY,11232,730 3rd Avenue,Kings,40.663000,-74.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,2019
2,1003742,1.100385e+11,31st Street Landfill,WESTCHESTER,IL,60154,11700 W 31ST ST,COOK COUNTY,41.834962,-87.916392,...,NaN,NaN,18678.50,NaN,NaN,NaN,N,N,N,2019
3,1003188,1.100006e+11,3M BROWNWOOD,BROWNWOOD,TX,76801,4501 HIGHWAY 377 SOUTH,BROWN COUNTY,31.671177,-98.996513,...,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,2019
4,1005043,1.100712e+11,3M CO,MAPLEWOOD,MN,55144,NaN,RAMSEY COUNTY,44.951000,-92.995900,...,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6545,1013667,1.100707e+11,Wadsworth,Seville,OH,44273,8793 Guilford Rd,MEDINA COUNTY,41.033572,-81.832417,...,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,2020
6546,1002079,1.100712e+11,Wamsutter Compressor Station,Wamsutter,WY,82336,20 Rasmussen Rd,SWEETWATER COUNTY,41.750585,-108.190306,...,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,2020
6547,1012921,1.100712e+11,Washington Court House Compressor Station,Washington Court House,OH,43160,8233 Old US 35 NW,FAYETTE COUNTY,39.594142,-83.540226,...,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,2020
6548,1006154,1.100712e+11,Waterloo Compressor Station,Waterloo,IA,50701,1508 East Schrock Road,BLACK HAWK COUNTY,42.399463,-92.327859,...,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,2020
6549,1008055,1.100712e+11,White Pigeon Compressor Station,White Pigeon,MI,49099,68536 A Road,ST. JOSEPH COUNTY,41.803260,-85.584270,...,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,2020

In [14]:
url = "https://lukashager.netlify.app/econ-481/data/ghgp_data_2019.xlsx"
# https://lukashager.netlify.app/econ-481/data/ghgp_data_parent_company_09_2023.xlsb
# https://lukashager.netlify.app/econ-481/data/ghgp_data_2019.xlsx
# https://lukashager.netlify.app/econ-481/data/ghgp_data_2020.xlsx
# https://lukashager.netlify.app/econ-481/data/ghgp_data_2021.xlsx
# https://lukashager.netlify.app/econ-481/data/ghgp_data_2022.xlsx
# pd.read_excel(url, header=3, sheet_name='Direct Emitters').head()

In [17]:
!pip install pyxlsb

Collecting pyxlsb
  Downloading pyxlsb-1.0.10-py2.py3-none-any.whl.metadata (2.5 kB)
Downloading pyxlsb-1.0.10-py2.py3-none-any.whl (23 kB)
Installing collected packages: pyxlsb
Successfully installed pyxlsb-1.0.10

In [24]:
url = "https://lukashager.netlify.app/econ-481/data/ghgp_data_parent_company_09_2023.xlsb"

pd.read_excel(url, engine='pyxlsb', sheet_name='2020').head()

,GHGRP FACILITY ID,FRS ID (FACILITY),REPORTING YEAR,FACILITY NAME,FACILITY ADDRESS,FACILITY CITY,FACILITY STATE,FACILITY ZIP,FACILITY COUNTY,PARENT COMPANY NAME,PARENT CO. STREET ADDRESS,PARENT CO. CITY,PARENT CO. STATE,PARENT CO. ZIP,PARENT CO. PERCENT OWNERSHIP,FACILITY NAICS CODE
0,1000001,1.100005e+11,2020,PSE Ferndale Generating Station,5105 LAKE TERRELL ROAD,FERNDALE,WA,98248,WHATCOM COUNTY,PUGET HOLDINGS LLC,PO Box 97034,Bellevue,WA,98009,100.0,221112
1,1000002,1.100412e+11,2020,Ardagh Glass Inc. (Dunkirk),524 E. CENTER STREET,DUNKIRK,IN,47336,JAY COUNTY,ARDAGH GLASS INC,1209 Orange Street,Wilmington,DE,19801,100.0,327213
2,1000003,1.100015e+11,2020,Ardagh Glass Inc. (Henderson),620 Facet Road,Henderson,NC,27537,VANCE COUNTY,ARDAGH GLASS INC,1209 Orange Street,Wilmington,DE,19801,100.0,327213
3,1000005,1.100005e+11,2020,Ardagh Glass Inc. (Madera),24441 AVENUE 12 & ROAD 24 1/2,MADERA,CA,93637,MADERA COUNTY,ARDAGH GLASS INC,1209 Orange Street,Wilmington,DE,19801,100.0,327213
4,1000007,1.100070e+11,2020,AMERICAN GYPSUM - BERNALILLO (WALLBOARD) PLANT,1000 N HILL RD,BERNALILLO,NM,87004,SANDOVAL COUNTY,EAGLE MATERIALS INC,5960 Berkshire Lane Suite 800,Dallas,TX,75225,100.0,327420

In [19]:
url = "https://lukashager.netlify.app/econ-481/data/ghgp_data_parent_company_09_2023.xlsb"

# Use the ExcelFile class to open the Excel file
with pd.ExcelFile(url, engine='pyxlsb') as xls:
    sheet_names = xls.sheet_names  # Get a list of all sheet names in the file

# Print the sheet names
print("Number of tabs:", len(sheet_names))
print("Tab names:", sheet_names)

Number of tabs: 13
Tab names: ['2022', '2021', '2020', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010']

In [25]:
# Exercise 2
import pandas as pd

def import_parent_companies(years: list) -> pd.DataFrame:
    """
    This function takes as its argument a list of years.
    It returns a concatenated DataFrame of the corresponding tabs in the parent companies excel sheet.
    It will add a variable year that references the year from which the data is pulled and
    remove any row that is entirely null values. No column use as index.
    """
    full_df = []

    for year in years:
        exl_path = "https://lukashager.netlify.app/econ-481/data/ghgp_data_parent_company_09_2023.xlsb"
        temp_df = pd.read_excel(exl_path, sheet_name=str(year))
        temp_df['year'] = year
        full_df.append(temp_df)

    
    return pd.concat(full_df).dropna(how='all')

In [42]:
#test2 = import_parent_companies([2019,2020,2021])
#sum(test2.isna().all(axis=1)
#test2.isna().sum()
test1.columns

Index(['Facility Id', 'FRS Id', 'Facility Name', 'City', 'State', 'Zip Code',
       'Address', 'County', 'Latitude', 'Longitude', 'Primary NAICS Code',
       'Industry Type (subparts)', 'Industry Type (sectors)',
       'Total reported direct emissions', 'CO2 emissions (non-biogenic) ',
       'Methane (CH4) emissions ', 'Nitrous Oxide (N2O) emissions ',
       'HFC emissions', 'PFC emissions', 'SF6 emissions ', 'NF3 emissions',
       'Other Fully Fluorinated GHG emissions', 'HFE emissions',
       'Very Short-lived Compounds emissions', 'Other GHGs (metric tons CO2e)',
       'Biogenic CO2 emissions (metric tons)', 'Stationary Combustion',
       'Electricity Generation', 'Adipic Acid Production',
       'Aluminum Production', 'Ammonia Manufacturing', 'Cement Production',
       'Electronics Manufacture', 'Ferroalloy Production',
       'Fluorinated GHG Production', 'Glass Production',
       'HCFC–22 Production from HFC–23 Destruction', 'Hydrogen Production',
       'Iron and Steel Production', 'Lead Production', 'Lime Production',
       'Magnesium Production', 'Miscellaneous Use of Carbonates',
       'Nitric Acid Production',
       'Petroleum and Natural Gas Systems – Offshore Production',
       'Petroleum and Natural Gas Systems – Processing',
       'Petroleum and Natural Gas Systems – Transmission/Compression',
       'Petroleum and Natural Gas Systems – Underground Storage',
       'Petroleum and Natural Gas Systems – LNG Storage',
       'Petroleum and Natural Gas Systems – LNG Import/Export',
       'Petrochemical Production', 'Petroleum Refining',
       'Phosphoric Acid Production', 'Pulp and Paper Manufacturing',
       'Silicon Carbide Production', 'Soda Ash Manufacturing',
       'Titanium Dioxide Production', 'Underground Coal Mines',
       'Zinc Production', 'Municipal Landfills',
       'Industrial Wastewater Treatment',
       'Manufacture of Electric Transmission and Distribution Equipment',
       'Industrial Waste Landfills',
       'Is some CO2 collected on-site and used to manufacture other products and therefore not emitted from the affected manufacturing process unit(s)? (as reported under Subpart G or S)',
       'Is some CO2 reported as emissions from the affected manufacturing process unit(s) under Subpart AA, G or P collected and transferred off-site or injected (as reported under Subpart PP)?',
       'Does the facility employ continuous emissions monitoring? ', 'year'],
      dtype='object')

In [68]:
test2check = import_parent_companies([2019,2020])
test2check

,GHGRP FACILITY ID,FRS ID (FACILITY),REPORTING YEAR,FACILITY NAME,FACILITY ADDRESS,FACILITY CITY,FACILITY STATE,FACILITY ZIP,FACILITY COUNTY,PARENT COMPANY NAME,PARENT CO. STREET ADDRESS,PARENT CO. CITY,PARENT CO. STATE,PARENT CO. ZIP,PARENT CO. PERCENT OWNERSHIP,FACILITY NAICS CODE,year
0,1000001,1.100005e+11,2019,PSE Ferndale Generating Station,5105 LAKE TERRELL ROAD,FERNDALE,WA,98248,WHATCOM COUNTY,PUGET SOUND ENERGY,10885 NE 4th St,Bellevue,WA,98004,100.0,221112,2019
1,1000002,1.100412e+11,2019,Ardagh Glass Inc. (Dunkirk),524 E. CENTER STREET,DUNKIRK,IN,47336,JAY COUNTY,ARDAGH GLASS INC,1209 Orange Street,Wilmington,DE,19801,100.0,327213,2019
2,1000003,1.100015e+11,2019,Ardagh Glass Inc. (Henderson),620 Facet Road,Henderson,NC,27537,VANCE COUNTY,ARDAGH GLASS INC,1209 Orange Street,Wilmington,DE,19801,100.0,327213,2019
3,1000004,1.100008e+11,2019,Ardagh Glass Inc. (Lincoln),1200 NORTH LOGAN STREET,LINCOLN,IL,62656,LOGAN COUNTY,ARDAGH GLASS INC,1209 Orange Street,Wilmington,DE,19801,100.0,327213,2019
4,1000005,1.100005e+11,2019,Ardagh Glass Inc. (Madera),24441 AVENUE 12 & ROAD 24 1/2,MADERA,CA,93637,MADERA COUNTY,ARDAGH GLASS INC,1209 Orange Street,Wilmington,DE,19801,100.0,327213,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9224,1014668,NaN,2020,WTG Hugoton - GB Stevens County #1,1548 State Highway 25,Hugoton,KS,67951,NaN,WEST TEXAS GAS INC,303 Veterans Airpark Lane,Midland,TX,79705,100.0,486210,2020
9225,1014698,1.100703e+11,2020,Norbord South Carolina Inc.,564 Woodyard Road,Kinards,SC,29355,LAURENS COUNTY,WEST FRASER INC,"1900 Exeter Road, Suite 105",Germantown,TN,38138,100.0,321219,2020
9226,1014703,1.100714e+11,2020,"Tyson Fresh Meats, Inc. - WWTP",NaN,Holcomb,KS,67851,FINNEY COUNTY,TYSON FOODS INC,2200 W Don Tyson Parkway,Springdale,AR,72762,100.0,311611,2020
9227,1014712,NaN,2020,GCC Supply & Trading LLC,"3773 Richmond Avenue, STE 250",Houston,TX,77046,NaN,GCC Supply & Trading LLC,"3773 Richmond Ave, Ste 250",Houston,TX,77046,100.0,424720,2020
9228,1014727,NaN,2020,Capitan Energy 430,415 Who Who Dr,Carlsbad,NM,88220,NaN,Capitan Energy,415 Who Who Dr,Carlsbad,NM,88220,100.0,211120,2020

In [31]:
# Exercise 3
def n_null(df: pd.DataFrame, col: str) -> int:
    """
    This function takes as its arguments a DataFrame and a column name.
    It returns an integer corresponding to the number of null values in that column
    """
    return df[col].isna().sum()

In [46]:
print(n_null(test1, 'FRS Id'), n_null(test1, 'Facility Id'))
print("use Facility Id better")

221 0
use Facility Id better

In [58]:
emis_df = import_yearly_data([2019, 2020, 2021, 2022])
parent_df = import_parent_companies([2019, 2020, 2021, 2022])
parent_df.head(n=3)

,GHGRP FACILITY ID,FRS ID (FACILITY),REPORTING YEAR,FACILITY NAME,FACILITY ADDRESS,FACILITY CITY,FACILITY STATE,FACILITY ZIP,FACILITY COUNTY,PARENT COMPANY NAME,PARENT CO. STREET ADDRESS,PARENT CO. CITY,PARENT CO. STATE,PARENT CO. ZIP,PARENT CO. PERCENT OWNERSHIP,FACILITY NAICS CODE,year
0,1000001,1.100005e+11,2019,PSE Ferndale Generating Station,5105 LAKE TERRELL ROAD,FERNDALE,WA,98248,WHATCOM COUNTY,PUGET SOUND ENERGY,10885 NE 4th St,Bellevue,WA,98004,100.0,221112.0,2019
1,1000002,1.100412e+11,2019,Ardagh Glass Inc. (Dunkirk),524 E. CENTER STREET,DUNKIRK,IN,47336,JAY COUNTY,ARDAGH GLASS INC,1209 Orange Street,Wilmington,DE,19801,100.0,327213.0,2019
2,1000003,1.100015e+11,2019,Ardagh Glass Inc. (Henderson),620 Facet Road,Henderson,NC,27537,VANCE COUNTY,ARDAGH GLASS INC,1209 Orange Street,Wilmington,DE,19801,100.0,327213.0,2019

In [57]:
emis_df.head(n=3)

,Facility Id,FRS Id,Facility Name,City,State,Zip Code,Address,County,Latitude,Longitude,...,Underground Coal Mines,Zinc Production,Municipal Landfills,Industrial Wastewater Treatment,Manufacture of Electric Transmission and Distribution Equipment,Industrial Waste Landfills,Is some CO2 collected on-site and used to manufacture other products and therefore not emitted from the affected manufacturing process unit(s)? (as reported under Subpart G or S),"Is some CO2 reported as emissions from the affected manufacturing process unit(s) under Subpart AA, G or P collected and transferred off-site or injected (as reported under Subpart PP)?",Does the facility employ continuous emissions monitoring?,year
0,1004377,1.100438e+11,121 REGIONAL DISPOSAL FACILITY,MELISSA,TX,75454,3820 SAM RAYBURN HIGHWAY,COLLIN COUNTY,33.298570,-96.535860,...,NaN,NaN,518680.25,NaN,NaN,NaN,N,N,N,2019
1,1000112,1.100712e+11,23rd and 3rd,BROOKLYN,NY,11232,730 3rd Avenue,Kings,40.663000,-74.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,2019
2,1003742,1.100385e+11,31st Street Landfill,WESTCHESTER,IL,60154,11700 W 31ST ST,COOK COUNTY,41.834962,-87.916392,...,NaN,NaN,18678.50,NaN,NaN,NaN,N,N,N,2019

In [64]:
# Exercise 4
def clean_data(emissions_data: pd.DataFrame, parent_data: pd.DataFrame) -> pd.DataFrame:
    """
    This function takes as its arguments a concatenated DataFrame of emissions sheets and a concatenated DataFrame of parent companies.
    Performs a left join on the emissions_data and parent_data DataFrames using 'year' and 'Facility Id'
    from emissions_data and 'year' and 'GHGRP FACILITY ID' from parent_data as join keys.
    
    Subsets the resulting DataFrame to include only the following columns: 'Facility Id', 'year', 'State',
    'Industry Type (sectors)', 'Total reported direct emissions', 'PARENT CO. STATE', and 'PARENT CO. PERCENT OWNERSHIP'.
    
    Return cleaned DataFrame with all column names to lower-case.
    """
    full_df = pd.merge(emissions_data, parent_data,
                       left_on=['year', 'Facility Id'], right_on=['year', 'GHGRP FACILITY ID'], how='left')
    col_subset = ['Facility Id', 'year', 'State',
                  'Industry Type (sectors)', 'Total reported direct emissions', 'PARENT CO. STATE', 'PARENT CO. PERCENT OWNERSHIP']
    subset_df = full_df[col_subset]
    subset_df.columns = [col.lower() for col in col_subset]
    return subset_df

In [67]:
test4 = clean_data(emis_df, parent_df)
test4.head(n=5)

,facility id,year,state,industry type (sectors),total reported direct emissions,parent co. state,parent co. percent ownership
0,1004377,2019,TX,Waste,518680.250,TX,100.0
1,1000112,2019,NY,Power Plants,44658.384,NY,100.0
2,1003742,2019,IL,Waste,18925.400,IL,100.0
3,1003188,2019,TX,Minerals,30571.636,MN,100.0
4,1005043,2019,MN,Other,106258.176,MN,100.0

In [79]:
# Exercise 5
def aggregate_emissions(df: pd.DataFrame, group_vars: list) -> pd.DataFrame:
    """
    Some docstrings.
    """
    return df.groupby(group_vars)[['total reported direct emissions', 'parent co. percent ownership']].agg(['min', 'median', 'mean', 'max']).sort_values(('total reported direct emissions', 'mean'), ascending=False)

In [69]:
test4.groupby('state')

Index(['facility id', 'year', 'state', 'industry type (sectors)',
       'total reported direct emissions', 'parent co. state',
       'parent co. percent ownership'],
      dtype='object')

In [85]:
st_yr = aggregate_emissions(clean_data(import_yearly_data([2019, 2020, 2021, 2022]), import_parent_companies([2019, 2020, 2021, 2022])), ['year', 'state'])
st_yr2 = aggregate_emissions(clean_data(import_yearly_data([2019, 2020, 2021, 2022]), import_parent_companies([2019, 2020, 2021, 2022])), ['facility id', 'state'])
st_yr3 = aggregate_emissions(clean_data(import_yearly_data([2019, 2020, 2021, 2022]), import_parent_companies([2019, 2020, 2021, 2022])), ['year', 'state', 'parent co. state'])

In [87]:
len(st_yr2)

6923

In [78]:
test4.groupby('state')[['total reported direct emissions', 'parent co. percent ownership']].agg(['min', 'median', 'mean', 'max']).sort_values(('total reported direct emissions', 'mean'), ascending=False)

      total reported direct emissions                               \
                                  min         median          mean
state
MT                             30.800  153664.012000  2.126718e+06
WY                              0.000  191281.676000  1.194204e+06
AR                              0.000   75585.833000  1.021846e+06
IA                              0.000  101493.534000  9.207591e+05
UT                             76.600   77594.000000  8.935823e+05
MO                              0.000   62212.216000  8.046185e+05
AZ                              0.000   64581.875000  8.025884e+05
NM                              0.000   57389.800166  7.849870e+05
IN                              0.000   76299.257000  7.178579e+05
CO                              0.000   71068.750000  7.147599e+05
FL                              0.000  111299.609000  6.384314e+05
PR                              0.000   85777.400000  6.381822e+05
ND                             33.300   87095.422000  6.293365e+05
WV                              0.000   75690.608000  6.175232e+05
GA                           2096.392   64302.312000  6.072883e+05
PA                              0.000   60045.011000  5.561534e+05
WI                             37.600   64854.379000  5.460472e+05
KY                              0.000   68480.125000  5.391597e+05
AL                              0.100  205846.630000  4.701201e+05
TX                              0.000   84742.250000  4.630561e+05
DE                           8162.750   51146.000000  4.550384e+05
NV                            233.300  201592.827000  4.531690e+05
OH                              0.000   70298.297000  4.404255e+05
MS                            555.750   62528.690000  4.253883e+05
AK                            161.700  148964.248000  4.162462e+05
MI                              0.000   55689.940000  4.045110e+05
NC                            128.500   67818.500000  4.020216e+05
NJ                             37.100   53672.542000  3.866419e+05
MN                              0.000   65451.662000  3.834768e+05
IL                              0.000   55911.950000  3.816255e+05
MD                              0.000   91909.153000  3.703015e+05
CT                           2728.250   84853.224000  3.692760e+05
NE                            705.550   66907.964000  3.479976e+05
LA                              0.000   66134.898000  3.454469e+05
SC                              0.000   65521.004000  3.404786e+05
RI                           4688.098  194906.037000  3.361734e+05
VA                              0.000   71062.130000  3.167178e+05
TN                              0.000   65651.000000  3.102696e+05
KS                            160.100   54399.644000  2.999569e+05
OK                              0.000   56979.550000  2.963832e+05
OR                            701.132   61937.590182  2.887881e+05
SD                             86.800   71398.732000  2.641368e+05
WA                              0.000   65848.300000  2.578627e+05
HI                              0.000   80985.125000  2.512349e+05
VI                            235.000  267781.180000  2.446349e+05
CA                              0.000   46851.324000  2.273039e+05
NY                              0.000   51551.750000  1.700638e+05
GU                           3370.894   54233.572000  1.555728e+05
NH                            853.136   50082.162000  1.506816e+05
ID                              0.000   68670.700000  1.349919e+05
MA                            734.750   45655.808000  1.325023e+05
ME                           2940.611   38877.338000  9.963233e+04
VT                          21684.764   36047.154000  8.351724e+04
DC                          14094.092   34986.480000  5.449216e+04

                    parent co. percent ownership
                max                          min  median        mean    max
state
MT     1.427756e+07                     5.110000  100.00   82.222222  100.0
WY     1.157398e+07                     0.000295  100.00   69.051191  100.0
AR     7.681771e+06                     0.500000  100.00   82.217573  100.0
IA     8.035653e+06                     0.000000  100.00   78.036202  100.0
UT     9.238311e+06                     2.080000  100.00   92.882562  100.0
MO     1.586076e+07                     2.000000  100.00   93.512304  100.0
AZ     1.090004e+07                     1.000000  100.00   89.465586  100.0
NM     9.813100e+06                     0.700000  100.00   78.972138  100.0
IN     1.157745e+07                     0.000000  100.00   94.736842  100.0
CO     8.395394e+06                     4.190000  100.00   86.796117  100.0
FL     9.204483e+06                     1.000000  100.00   92.348285  100.0
PR     4.455499e+06                   100.000000  100.00  100.000000  100.0
ND     9.451219e+06                     0.660000  100.00   87.456472  100.0
WV     1.179000e+07                    35.000000  100.00   96.367521  100.0
GA     1.376442e+07                     0.000000  100.00   91.807895  100.0
PA     1.054635e+07                     0.000000  100.00   94.758710  100.0
WI     7.603279e+06                     0.700000  100.00   93.140794  100.0
KY     1.038561e+07                     0.000000  100.00   98.664122  100.0
AL     2.177544e+07                     0.000000  100.00   70.685994  100.0
TX     1.391135e+07                     0.000000  100.00   88.532070  100.0
DE     3.680307e+06                     0.000000  100.00   90.588235  100.0
NV     2.669115e+06                    38.000000  100.00   89.204545  100.0
OH     1.378822e+07                     0.000000  100.00   93.622921  100.0
MS     6.172185e+06                     0.100000  100.00   87.761538  100.0
AK     3.024876e+06                     0.020000   92.52   64.061595  100.0
MI     1.514472e+07                     0.000000  100.00   95.116537  100.0
NC     7.394204e+06                     8.000000  100.00   97.813121  100.0
NJ     2.801684e+06                     1.000000  100.00   89.843750  100.0
MN     1.121090e+07                     1.000000  100.00   94.054054  100.0
IL     1.273715e+07                     1.000000  100.00   95.811518  100.0
MD     2.604664e+06                    25.000000  100.00   94.339623  100.0
CT     2.189121e+06                    10.790000  100.00   90.532485  100.0
NE     8.019949e+06                     0.007000  100.00   88.922150  100.0
LA     1.000546e+07                     0.040000  100.00   81.420578  100.0
SC     8.554334e+06                    10.000000  100.00   96.473552  100.0
RI     1.356222e+06                   100.000000  100.00  100.000000  100.0
VA     4.055743e+06                    10.000000  100.00   96.421846  100.0
TN     1.072012e+07                    10.000000  100.00   97.711670  100.0
KS     9.449839e+06                     0.755100  100.00   89.892455  100.0
OK     3.923476e+06                     3.440000  100.00   90.013495  100.0
OR     2.544637e+06                    10.000000  100.00   95.708155  100.0
SD     2.834375e+06                    22.700000  100.00   94.838710  100.0
WA     8.000387e+06                    33.330000  100.00   96.325404  100.0
HI     2.018125e+06                    30.000000  100.00   96.551724  100.0
VI     9.018858e+05                   100.000000  100.00  100.000000  100.0
CA     6.263565e+06                     0.000000  100.00   87.595972  100.0
NY     2.912919e+06                     0.000000  100.00   93.953488  100.0
GU     6.269188e+05                   100.000000  100.00  100.000000  100.0
NH     1.326883e+06                   100.000000  100.00  100.000000  100.0
ID     7.221712e+05                     0.000000  100.00   96.732026  100.0
MA     1.768903e+06                     0.440000  100.00   95.070423  100.0
ME     9.208089e+05                     0.011680  100.00   78.260930  100.0
VT     2.971934e+05                   100.000000  100.00  100.000000  100.0
DC     1.303497e+05                   100.000000  100.00  100.000000  100.0